server:
  port: 8082

spring:
  application:
    name: hibernate-mentoring
  datasource:
    url: jdbc:postgresql://localhost:5433/mentoring
    username: dev
    password: Ab123456
    hikari:
      schema: hibernate_course
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS ${spring.datasource.hikari.schema}
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.yml
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate
